# Baseline Gender Biased Token Classifiers

* Supervised learning
    * Train, Validate, and (Blind) Test Data: under directory ../data/token_clf_data/model_input/
* Multilabel classification
    * 3 categories of labels:
        1. Person Name: Unknown, Non-binary, Feminine, Masculine
        2. Linguistic: Generalization, Gendered Pronoun, Gendered Role
        3. Contextual: Empowering, Occupation, Omission, Stereotype
* Also could try a [classifier chain](https://scikit-learn.org/stable/modules/multiclass.html#classifierchain)!

***

**Table of Contents**

[0.](#0) Preprocessing

[1.](#1) Logistic Regression (LR)

[2.](#2) Random Forest

[3.](#3) Support Vector Machines (SVM) (a.k.a. support vector classification (SVC))

[4.](#4) Error Analysis

***

**References**
* https://scikit-learn.org/stable/modules/preprocessing_targets.html#preprocessing-targets 
* https://towardsdatascience.com/named-entity-recognition-and-classification-with-scikit-learn-f05372f07ba2
* Text Analysis with Python for Social Scienctists (Hovy, 2022)

Load necessary libraries:

In [11]:
# For custom functions and variables
import utils, config

# For data analysis
import pandas as pd
import numpy as np
import os, re

# For creating directories
from pathlib import Path

# For visualization
import matplotlib.pyplot as plt
import seaborn as sns

# For preprocessing
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize, sent_tokenize
# from nltk.corpus import stopwords
from nltk.tag import pos_tag

# For classifcation
from sklearn.preprocessing import LabelEncoder, MultiLabelBinarizer
from sklearn.multiclass import OneVsRestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer, TfidfTransformer, CountVectorizer
from sklearn.feature_extraction import DictVectorizer  # does binary one-hot encoding if features are strings
from sklearn.linear_model import LogisticRegression
# from sklearn.svm import SVC
# from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix, multilabel_confusion_matrix, plot_confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import precision_recall_fscore_support, f1_score

# Why won't these import?  They are installed...
#---------------------
# import sklearn_crfsuite
# For model debugging
# import eli5

<a id="0"></a>
## 0. Preprocessing

Load the train and validation (dev) data:

In [31]:
df_train = pd.read_csv(config.tokc_path+"model_input/token_train.csv", index_col=0)
df_train = df_train.loc[df_train.field != "Identifier"]
df_dev = pd.read_csv(config.tokc_path+"model_input/token_validate.csv", index_col=0)
df_dev = df_dev.loc[df_dev.field != "Identifier"]
print(df_train.shape, df_dev.shape)
df_train.head()

(470070, 8) (158662, 8)

,description_id,sentence_id,ann_id,token_id,token,tag,field,subset
3,1,1,99999,3,Title,O,Title,train
4,1,1,99999,4,:,O,Title,train
5,1,1,99999,5,Papers,O,Title,train
6,1,1,99999,6,of,O,Title,train
7,1,1,14384,7,The,B-Unknown,Title,train

Remove Non-binary labels as these were mistaken labels identified early on that were meant to be excluded, and because only one token has this label, it prevents the data from being input into the models with cross-validation.

In [5]:
# # df_train.loc[df_train.tag == "B-Nonbinary"]
# df_train.loc[df_train.token_id == 230697]
# # df_train.loc[df_train.tag == "I-Nonbinary"]
# df_train.loc[df_train.token_id == 230697]
# df_dev.loc[df_dev.tag == "B-Nonbinary"]  # No results
# df_dev.loc[df_dev.tag == "I-Nonbinary"]  # No results
df_train = df_train.loc[df_train.tag != "B-Nonbinary"]
df_train = df_train.loc[df_train.tag != "I-Nonbinary"]

In [6]:
df_train.shape

(470710, 8)

In [21]:
df_train.groupby("tag").size().reset_index(name="total")

                   tag   total
0           B-Feminine     927
1   B-Gendered-Pronoun    2475
2      B-Gendered-Role    2146
3     B-Generalization    1280
4          B-Masculine    3666
5         B-Occupation    2477
6           B-Omission    4447
7         B-Stereotype    1595
8            B-Unknown   12964
9           I-Feminine    2051
10  I-Gendered-Pronoun      31
11     I-Gendered-Role     434
12    I-Generalization     528
13         I-Masculine    5257
14        I-Occupation    2785
15          I-Omission    6895
16        I-Stereotype    3433
17           I-Unknown   27766
18                   O  389553

In [22]:
df_dev.groupby("tag").size().reset_index(name="total")

                   tag   total
0           B-Feminine     357
1   B-Gendered-Pronoun     833
2      B-Gendered-Role     767
3     B-Generalization     386
4          B-Masculine    1125
5         B-Occupation     866
6           B-Omission    1476
7         B-Stereotype     527
8            B-Unknown    4249
9           I-Feminine     949
10  I-Gendered-Pronoun      18
11     I-Gendered-Role     158
12    I-Generalization     165
13         I-Masculine    1568
14        I-Occupation     953
15          I-Omission    2282
16        I-Stereotype    1213
17           I-Unknown    9224
18                   O  131720

If not classifying all labels at once, consider only the rows with tags for the select subset of labels:

In [44]:
# label_subset = ["B-Stereotype", "I-Stereotype", "B-Omission", "I-Omission", "B-Occupation", "I-Occupation"]
# label_subset = ["B-Unknown", "I-Unknown", "B-Feminine", "I-Feminine", "B-Masculine", "I-Masculine", "B-Nonbinary", "I-Nonbinary"]
# label_subset = ["B-Generalization", "I-Generalization", "B-Gendered-Role", "I-Gendered-Role", "B-Gendered-Pronoun", "I-Gendered-Pronoun"]
# df_train = df_train.loc[df_train.tag.isin(label_subset)]
# df_dev = df_dev.loc[df_dev.tag.isin(label_subset)]
# print(df_train.shape, df_dev.shape)

#### Normalization 
Lemmatize the tokens:

In [7]:
lmtzr = WordNetLemmatizer()

In [8]:
tokens_train = list(df_train.token)
lemmas_train = [lmtzr.lemmatize(token) for token in tokens_train]
tokens_dev = list(df_dev.token)
lemmas_dev = [lmtzr.lemmatize(token) for token in tokens_dev]

In [9]:
df_train.insert((list(df_train.columns).index("token")+1), "lemma", lemmas_train)
df_dev.insert((list(df_dev.columns).index("token")+1), "lemma", lemmas_dev)

In [10]:
# df_train.tail()
df_dev.head()

,description_id,sentence_id,ann_id,token_id,token,lemma,tag,field,subset
172,3,5,99999,154,After,After,O,Biographical / Historical,dev
173,3,5,14379,155,his,his,B-Gendered-Pronoun,Biographical / Historical,dev
174,3,5,99999,156,ordination,ordination,O,Biographical / Historical,dev
175,3,5,14380,157,he,he,B-Gendered-Pronoun,Biographical / Historical,dev
176,3,5,99999,158,spent,spent,O,Biographical / Historical,dev

#### Part-of-Speech Tagging

In [35]:
df_sent = pd.read_csv(config.tokc_path+"sentences.csv",index_col=0)
print(df_sent.shape)
# Ignore sentences that aren't in input data
df_test = pd.read_csv(config.tokc_path+"model_input/token_test.csv", index_col=0)
df_test = df_test.loc[df_test.field != "Identifier"]
all_sentids = []
for df in [df_train, df_dev, df_test]:
    sentids = set(list(df.sentence_id.unique()))
    all_sentids += list(sentids)
all_sentids = list(set(all_sentids))
df_sent = df_sent.loc[df_sent.sentence_id.isin(all_sentids)]  
print(df_sent.shape)
df_sent.head()

(42030, 4)
(41692, 4)

,sentence_id,description_id,sentences,sent_offsets
1,1,1,Title:\nPapers of The Very Rev Prof James Whyt...,"(17, 76)"
2,2,2,"Scope and Contents:\nSermons and addresses, 19...","(77, 633)"
3,3,3,Biographical / Historical:\nProfessor James Ai...,"(634, 789)"
4,4,3,He was educated at Daniel Stewart's College an...,"(789, 907)"
5,5,3,After his ordination he spent three years as a...,"(907, 1032)"

In [38]:
sentences = list(df_sent.sentences)
tokenized_sentences = [nltk.word_tokenize(s) for s in sentences]
tagged_sentences = [nltk.pos_tag(s) for s in tokenized_sentences]
print(sentences[0])
print(tokenized_sentences[0])
print(tagged_sentences[0])

Title:
Papers of The Very Rev Prof James Whyte (1920-2005)
['Title', ':', 'Papers', 'of', 'The', 'Very', 'Rev', 'Prof', 'James', 'Whyte', '(', '1920-2005', ')']
[('Title', 'NN'), (':', ':'), ('Papers', 'NNS'), ('of', 'IN'), ('The', 'DT'), ('Very', 'NNP'), ('Rev', 'NNP'), ('Prof', 'NNP'), ('James', 'NNP'), ('Whyte', 'NNP'), ('(', '('), ('1920-2005', 'CD'), (')', ')')]

In [41]:
# sentid_to_postagged = dict(zip(list(df_sent.sentence_id), tagged_sentences))
df_pos = pd.DataFrame({"sentence_id":df_sent.sentence_id, "postagged_sentence":tagged_sentences})
df_pos = df_pos.explode("postagged_sentence")
df_pos.head()

   sentence_id postagged_sentence
1            1        (Title, NN)
1            1             (:, :)
1            1      (Papers, NNS)
1            1           (of, IN)
1            1          (The, DT)

In [42]:
df_pos.shape

(752509, 2)

In [45]:
df_pos_train = df_pos.loc[df_pos.sentence_id.isin(list(df_train.sentence_id))]
# df_train.shape < df_pos_train.shape because many tokens have multiple IOB tags
print(df_pos_train.shape)

(451445, 2)

In [47]:
# df_train_imploded = utils.implodeDataFrame(df_train, ["token_id"])
# print(df_train_imploded.shape) # 451682 - not the same as df_pos_train

(451682, 7)

**Iterate through postagged_sentences one by one and assign token id, so order preserved...**

In [52]:
# subdf_train = df_train[["sentence_id", "token_id", "token"]]
# subdf_train = subdf_train.drop_duplicates()
# assert subdf_train.shape[0] == len(list(df_train.token_id.unique()))
subdf_train_imploded = utils.implodeDataFrame(subdf_train, ["sentence_id"])
sent_tok_dict = subdf_train_imploded.to_dict(orient="records")
print(sent_tok_dict[1])

{'token_id': [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], 'token': ['Scope', 'and', 'Contents', ':', 'Sermons', 'and', 'addresses', ',', '1948-1996', ';', 'lectures', ',', '1949-1982', ';', 'class', 'notes', 'and', 'lecture', 'notes', ',', '1949-1982', ';', 'correspondence', ',', '1988-1989', 'and', '1964-1970', ';', 'newspaper', 'cuttings', ',', '1988-1989', 'and', '1964-1969', ';', 'publications', 'and', 'articles', ',', '1902-1970', ';', 'church', 'magazines', ',', '1929-1993', ';', 'conference', 'papers', ',', '1978', ';', 'moderatorial', 'papers', ',', '1988-1989', ';', 'University', 'Christian', 'Consultative', 'Group', 'papers', ',', '1970-1972', ';', 'Church', 'of', 'Scotland', 'and', 'the', 'Congregational', 'Union', 'of', 'Scotland', 'papers', ',', '1959-1967', ';', 'personal', 'papers', ',', '1848-1983', ';', 'photographs', '1911', 'and', '1960.See', 'also', 'External', 'Documents', '(', 'below', ')', '.']}

Binarize and encode the data:

In [31]:
v = DictVectorizer(sparse=True)
# mlb = MultiLabelBinarizer()
# labels2numbers = LabelEncoder()

In [32]:
feature_cols = ["sentence_id", "token"]  #"lemma"
target_col = "tag"
labels = list(np.unique(df_train.tag))
# labels2numbers = LabelEncoder()
# y = labels2numbers.fit_transform(labels)
# label_to_no = dict(zip(labels,list(y)))
# no_to_label = dict(zip(list(y),labels))
# print(label_to_no)

In [33]:
X_train = df_train[feature_cols]
X_train = v.fit_transform(X_train.to_dict('records'))  # v.fit() - make sure column count same as X_dev!
print(X_train.shape)

y_train = df_train[target_col].values
# # Convert the string labels to numeric labels
# y_train_numeric = utils.getNumericLabels(y_train, label_to_no)
# # Convert each iterable of iterables above to a multilabel format
# y_train_binarized = mlb.fit_transform(y_train_numeric)
# print(y_train.shape, y_train_binarized.shape)

(470710, 35979)

In [34]:
X_dev = df_dev[feature_cols]
# X_dev = df_dev.drop("tag", axis=1)
X_dev = v.transform(X_dev.to_dict('records'))
print(X_dev.shape)

y_dev = df_dev[target_col].values
# # Convert the string labels to numeric labels
# y_dev_numeric = utils.getNumericLabels(y_dev, label_to_no)
# # Convert each iterable of iterables above to a multilabel format
# y_dev_binarized = mlb.transform(y_dev_numeric)
# print(y_dev.shape, y_dev_binarized.shape)

(158836, 35979)

In [35]:
assert X_dev.shape[1] == X_train.shape[1], "The train and dev data must have the same number of columns."

<a id="1"></a>
## 1. Logistic Regression

In [64]:
log_reg = OneVsRestClassifier(LogisticRegression(solver="liblinear", multi_class="ovr", random_state=22))

In [71]:
clf = log_reg.fit(X_train, y_train_binarized)

In [72]:
predicted_dev = clf.predict(X_dev)
print(predicted_dev[0])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]

In [ ]:
# print("Contextual Labels Dev Accuracy on `token` col:", np.mean(predicted_dev == y_dev))  # 33%
# print("Person Name Labels Dev Accuracy on `token` col:", np.mean(predicted_dev == y_dev))  # 40%
# print("Linguistic Labels Dev Accuracy on `token` col:", np.mean(predicted_dev == y_dev))  # 76%
# print("Dev Accuracy (all labels) on `token` col:", np.mean(predicted_dev == y_dev))  # 90%
# print("Dev Accuracy (all labels) on `lemma` col:", np.mean(predicted_dev == y_dev))  # 90%
# print("Scaled Dev Accuracy (all labels) on `token` col:", np.mean(predicted_dev == y_dev_binarized))  # 99%

#### Performance

In [74]:
original_labels = mlb.classes_
dev_matrix = multilabel_confusion_matrix(y_dev_binarized, predicted_dev, labels=mlb.classes_)
df_dev_perf = utils.getPerformanceMetrics(y_dev_binarized, predicted_dev, dev_matrix, mlb.classes_, original_labels, no_to_label)
df_dev_perf

,labels,true_neg,false_neg,true_pos,false_pos,precision,recall,f_1
0,B-Feminine,158479,357,0,0,0.000000,0.0,0.000000
1,B-Gendered-Pronoun,158003,833,0,0,0.000000,0.0,0.000000
2,B-Gendered-Role,158069,767,0,0,0.000000,0.0,0.000000
3,B-Generalization,158450,386,0,0,0.000000,0.0,0.000000
4,B-Masculine,157711,1125,0,0,0.000000,0.0,0.000000
5,B-Occupation,157970,866,0,0,0.000000,0.0,0.000000
6,B-Omission,157360,1476,0,0,0.000000,0.0,0.000000
7,B-Stereotype,158309,527,0,0,0.000000,0.0,0.000000
8,B-Unknown,154587,4249,0,0,0.000000,0.0,0.000000
9,I-Feminine,157887,949,0,0,0.000000,0.0,0.000000
10,I-Gendered-Pronoun,158818,18,0,0,0.000000,0.0,0.000000
11,I-Gendered-Role,158678,158,0,0,0.000000,0.0,0.000000
12,I-Generalization,158671,165,0,0,0.000000,0.0,0.000000
13,I-Masculine,157268,1568,0,0,0.000000,0.0,0.000000
14,I-Occupation,157883,953,0,0,0.000000,0.0,0.000000
15,I-Omission,156554,2282,0,0,0.000000,0.0,0.000000
16,I-Stereotype,157623,1213,0,0,0.000000,0.0,0.000000
17,I-Unknown,149612,9224,0,0,0.000000,0.0,0.000000
18,O,0,0,131720,27116,0.829283,1.0,0.906675

In [79]:
print("Dev Accuracy (all labels) on `token` col:", np.mean(predicted_dev == y_dev_binarized))

Dev Accuracy (all labels) on `token` col: 0.9820297930603031

Try using cross-validation (stratified k fold, where k=3) with Logistic Regression:

In [76]:
k = 3 # number of folds

In [88]:
log_reg_cv = OneVsRestClassifier(LogisticRegressionCV(
    solver="liblinear", multi_class="ovr", cv=k, scoring="f1", random_state=22)  #max_iter=500, --> default is 100 iterations
                                )
clf1 = log_reg_cv.fit(X_train, y_train_binarized)
pred1_dev = clf1.predict(X_dev)
# print("Dev Accuracy (all labels) on `lemma` col:", np.mean(pred1_dev == y_dev))  # 90%
# print("Dev Accuracy (all labels) on `token` col:", np.mean(pred1_dev == y_dev))  # 90%
# from sklearn import metrics
# metrics.SCORERS.keys()
# print("Accuracy:", clf1.score(pred1_dev, y_dev_binarized))

In [85]:
original_labels = mlb.classes_
dev_matrix1 = multilabel_confusion_matrix(y_dev_binarized, pred1_dev, labels=mlb.classes_)
df_dev_perf1 = utils.getPerformanceMetrics(y_dev_binarized, pred1_dev, dev_matrix1, mlb.classes_, original_labels, no_to_label)
df_dev_perf1

,labels,true_neg,false_neg,true_pos,false_pos,precision,recall,f_1
0,B-Feminine,158479,357,0,0,0.000000,0.0,0.000000
1,B-Gendered-Pronoun,158003,833,0,0,0.000000,0.0,0.000000
2,B-Gendered-Role,158069,767,0,0,0.000000,0.0,0.000000
3,B-Generalization,158450,386,0,0,0.000000,0.0,0.000000
4,B-Masculine,157711,1125,0,0,0.000000,0.0,0.000000
5,B-Occupation,157970,866,0,0,0.000000,0.0,0.000000
6,B-Omission,157360,1476,0,0,0.000000,0.0,0.000000
7,B-Stereotype,158309,527,0,0,0.000000,0.0,0.000000
8,B-Unknown,154587,4249,0,0,0.000000,0.0,0.000000
9,I-Feminine,157887,949,0,0,0.000000,0.0,0.000000
10,I-Gendered-Pronoun,158818,18,0,0,0.000000,0.0,0.000000
11,I-Gendered-Role,158678,158,0,0,0.000000,0.0,0.000000
12,I-Generalization,158671,165,0,0,0.000000,0.0,0.000000
13,I-Masculine,157268,1568,0,0,0.000000,0.0,0.000000
14,I-Occupation,157883,953,0,0,0.000000,0.0,0.000000
15,I-Omission,156554,2282,0,0,0.000000,0.0,0.000000
16,I-Stereotype,157623,1213,0,0,0.000000,0.0,0.000000
17,I-Unknown,149612,9224,0,0,0.000000,0.0,0.000000
18,O,0,0,131720,27116,0.829283,1.0,0.906675

**QUESTION:** Are scores averaged across the 3 folds?

<a id="2"></a>
## 2. Perceptron

In [37]:
per = Perceptron(verbose=10, n_jobs=-1, max_iter=5)
clf2 = per.fit(X_train, y_train, labels)

ValueError: Provided ``coef_`` does not match dataset.

In [20]:
labels_noO = labels.copy()
labels_noO.pop()
print(classification_report(y_pred=per.predict(X_dev), y_true=y_dev, labels=labels_noO, zero_division=0))

                    precision    recall  f1-score   support

        B-Feminine       0.00      0.00      0.00       357
B-Gendered-Pronoun       0.00      0.00      0.00       833
   B-Gendered-Role       0.00      0.00      0.00       767
  B-Generalization       0.00      0.00      0.00       386
       B-Masculine       0.00      0.00      0.00      1125
      B-Occupation       0.00      0.00      0.00       866
        B-Omission       0.00      0.00      0.00      1476
      B-Stereotype       0.00      0.00      0.00       527
         B-Unknown       0.00      0.00      0.00      4249
        I-Feminine       0.00      0.00      0.00       949
I-Gendered-Pronoun       0.00      0.00      0.00        18
   I-Gendered-Role       0.00      0.00      0.00       158
  I-Generalization       0.00      0.00      0.00       165
       I-Masculine       0.00      0.00      0.00      1568
      I-Occupation       0.00      0.00      0.00       953
        I-Omission       0.00      0.00      0.00      2282
      I-Stereotype       0.00      0.00      0.00      1213
         I-Unknown       0.00      0.00      0.00      9224

         micro avg       0.00      0.00      0.00     27116
         macro avg       0.00      0.00      0.00     27116
      weighted avg       0.00      0.00      0.00     27116

<a id="3"></a>
## 3. Stochastic Gradient Descent

In [42]:
sgd = SGDClassifier()
clf3 = sgd.partial_fit(X_train, y_train, labels)

In [43]:
print(classification_report(y_pred=clf3.predict(X_dev), y_true=y_dev, labels=labels))

                    precision    recall  f1-score   support

        B-Feminine       0.00      0.00      0.00       357
B-Gendered-Pronoun       0.00      0.00      0.00       833
   B-Gendered-Role       0.00      0.00      0.00       767
  B-Generalization       0.00      0.00      0.00       386
       B-Masculine       0.00      0.00      0.00      1125
      B-Occupation       0.00      0.00      0.00       866
        B-Omission       0.00      0.00      0.00      1476
      B-Stereotype       0.00      0.00      0.00       527
         B-Unknown       0.00      0.00      0.00      4249
        I-Feminine       0.00      0.00      0.00       949
I-Gendered-Pronoun       0.00      0.00      0.00        18
   I-Gendered-Role       0.00      0.00      0.00       158
  I-Generalization       0.00      0.00      0.00       165
       I-Masculine       0.00      0.00      0.00      1568
      I-Occupation       0.00      0.00      0.00       953
        I-Omission       0.00      0.00      0.00      2282
      I-Stereotype       0.00      0.00      0.00      1213
         I-Unknown       0.00      0.00      0.00      9224
                 O       0.83      1.00      0.91    131720

          accuracy                           0.83    158836
         macro avg       0.04      0.05      0.05    158836
      weighted avg       0.69      0.83      0.75    158836